export { default as About} from './about';
export { default as Contact } from './contact';
export { default as Education } from './education';
export { default as Experience } from './experience';
export { default as Home } from './home';
export { default as Skill } from './skill';
export { default as Project } from './project';
export { default as BaseEntity } from './base-entity';
export { default as Attribute } from './attribute';
export { default as ClientLayout } from './layout';